name: Mono Download Test

on:
  push:
    branches:
      - master

jobs:
  Check-Module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12.1
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/tests" >> $GITHUB_ENV

      - name: Run Pytest
        run: pytest --verbose
